=== EmelyanovSI/phplabs/xml/lab5/lab5.dtd
<!ELEMENT shoeShop (season+)>

        <!ELEMENT season (gender+)>
        <!ATTLIST season name (summer|winter|demi-season) "demi-season">

        <!ELEMENT gender (type*|model*)+>
        <!ATTLIST gender sex (male|female|unisex) "unisex">

        <!ELEMENT model (type*)>
        <!ATTLIST model name CDATA #REQUIRED>

        <!ELEMENT type (modelName, image, weight, size, price, color, description)>
        <!ATTLIST type id CDATA #IMPLIED>

        <!ELEMENT modelName (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT weight (#PCDATA)>
        <!ELEMENT size (height, width, top)>
        <!ELEMENT height (#PCDATA)>
        <!ELEMENT width (#PCDATA)>
        <!ELEMENT top (#PCDATA)>

        <!ELEMENT price (#PCDATA)>
        <!ELEMENT color (#PCDATA)>
        <!ELEMENT description (#PCDATA)>

=== EmelyanovSI/phplabs/xml/lab5/lab5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shoeShop SYSTEM "lab5.dtd">

<shoeShop>

    <season name="summer">
        <gender sex="male">
            <model name="shoes">
                <type id="1">
                    <modelName>Some model one</modelName>
                    <image>img1.jpg</image>
                    <weight>10</weight>
                    <size>
                        <height>12</height>
                        <width>10</width>
                        <top>5</top>
                    </size>
                    <price>50</price>
                    <color>black</color>
                    <description>For going everywhere</description>
                </type>
                <type id="2">
                    <modelName>Some model two</modelName>
                    <image>img2.jpg</image>
                    <weight>16</weight>
                    <size>
                        <height>24</height>
                        <width>16</width>
                        <top>8</top>
                    </size>
                    <price>60</price>
                    <color>blue</color>
                    <description>For going everywhere</description>
                </type>
                <type id="3">
                    <modelName>Some model three</modelName>
                    <image>img3.jpg</image>
                    <weight>24</weight>
                    <size>
                        <height>32</height>
                        <width>20</width>
                        <top>12</top>
                    </size>
                    <price>80</price>
                    <color>white</color>
                    <description>For going everywhere</description>
                </type>
            </model>

            <model name="sandals">
                <type id="4">
                    <modelName>Some model one</modelName>
                    <image>img4.jpg</image>
                    <weight>10</weight>
                    <size>
                        <height>12</height>
                        <width>10</width>
                        <top>5</top>
                    </size>
                    <price>50</price>
                    <color>black</color>
                    <description>For going everywhere</description>
                </type>
                <type id="5">
                    <modelName>Some model two</modelName>
                    <image>img5.jpg</image>
                    <weight>16</weight>
                    <size>
                        <height>24</height>
                        <width>16</width>
                        <top>8</top>
                    </size>
                    <price>60</price>
                    <color>blue</color>
                    <description>For going everywhere</description>
                </type>
                <type id="6">
                    <modelName>Some model three</modelName>
                    <image>img6.jpg</image>
                    <weight>24</weight>
                    <size>
                        <height>32</height>
                        <width>20</width>
                        <top>12</top>
                    </size>
                    <price>80</price>
                    <color>white</color>
                    <description>For going everywhere</description>
                </type>
            </model>

            <model name="sneakers">
                <type id="7">
                    <modelName>Some model one</modelName>
                    <image>img7.jpg</image>
                    <weight>10</weight>
                    <size>
                        <height>12</height>
                        <width>10</width>
                        <top>5</top>
                    </size>
                    <price>50</price>
                    <color>black</color>
                    <description>For going everywhere</description>
                </type>
                <type id="8">
                    <modelName>Some model two</modelName>
                    <image>img8.jpg</image>
                    <weight>16</weight>
                    <size>
                        <height>24</height>
                        <width>16</width>
                        <top>8</top>
                    </size>
                    <price>60</price>
                    <color>blue</color>
                    <description>For going everywhere</description>
                </type>
                <type id="9">
                    <modelName>Some model three</modelName>
                    <image>img9.jpg</image>
                    <weight>24</weight>
                    <size>
                        <height>32</height>
                        <width>20</width>
                        <top>12</top>
                    </size>
                    <price>80</price>
                    <color>white</color>
                    <description>For going everywhere</description>
                </type>
            </model>
        </gender>
        <gender sex="female">
            <model name="shoes">
                <type id="10">
                    <modelName>Some model one</modelName>
                    <image>img1.jpg</image>
                    <weight>10</weight>
                    <size>
                        <height>12</height>
                        <width>10</width>
                        <top>5</top>
                    </size>
                    <price>50</price>
                    <color>black</color>
                    <description>For going everywhere</description>
                </type>
                <type id="11">
                    <modelName>Some model two</modelName>
                    <image>img2.jpg</image>
                    <weight>16</weight>
                    <size>
                        <height>24</height>
                        <width>16</width>
                        <top>8</top>
                    </size>
                    <price>60</price>
                    <color>blue</color>
                    <description>For going everywhere</description>
                </type>
                <type id="12">
                    <modelName>Some model three</modelName>
                    <image>img3.jpg</image>
                    <weight>24</weight>
                    <size>
                        <height>32</height>
                        <width>20</width>
                        <top>12</top>
                    </size>
                    <price>80</price>
                    <color>white</color>
                    <description>For going everywhere</description>
                </type>
            </model>

            <model name="sandals">
                <type id="13">
                    <modelName>Some model one</modelName>
                    <image>img4.jpg</image>
                    <weight>10</weight>
                    <size>
                        <height>12</height>
                        <width>10</width>
                        <top>5</top>
                    </size>
                    <price>50</price>
                    <color>black</color>
                    <description>For going everywhere</description>
                </type>
                <type id="14">
                    <modelName>Some model two</modelName>
                    <image>img5.jpg</image>
                    <weight>16</weight>
                    <size>
                        <height>24</height>
                        <width>16</width>
                        <top>8</top>
                    </size>
                    <price>60</price>
                    <color>blue</color>
                    <description>For going everywhere</description>
                </type>
                <type id="6">
                    <modelName>Some model three</modelName>
                    <image>img6.jpg</image>
                    <weight>24</weight>
                    <size>
                        <height>32</height>
                        <width>20</width>
                        <top>12</top>
                    </size>
                    <price>80</price>
                    <color>white</color>
                    <description>For going everywhere</description>
                </type>
            </model>

            <model name="sneakers">
                <type id="15">
                    <modelName>Some model one</modelName>
                    <image>img7.jpg</image>
                    <weight>10</weight>
                    <size>
                        <height>12</height>
                        <width>10</width>
                        <top>5</top>
                    </size>
                    <price>50</price>
                    <color>black</color>
                    <description>For going everywhere</description>
                </type>
                <type id="16">
                    <modelName>Some model two</modelName>
                    <image>img8.jpg</image>
                    <weight>16</weight>
                    <size>
                        <height>24</height>
                        <width>16</width>
                        <top>8</top>
                    </size>
                    <price>60</price>
                    <color>blue</color>
                    <description>For going everywhere</description>
                </type>
                <type id="17">
                    <modelName>Some model three</modelName>
                    <image>img9.jpg</image>
                    <weight>24</weight>
                    <size>
                        <height>32</height>
                        <width>20</width>
                        <top>12</top>
                    </size>
                    <price>80</price>
                    <color>white</color>
                    <description>For going everywhere</description>
                </type>
            </model>
        </gender>
    </season>

    <season name="winter">
